apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask-deployment
  labels:
    app: python-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask-deployment
  template:
    metadata:
      labels:
        app: python-flask-deployment
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: python-flask-deployment
        image: babymanchineella123/hotstar:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
