apiVersion: v1
kind: Service
metadata:
  name: python-flask-svc
  labels:
    app: python-flask-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: python-flask-svc
